### ISSUE TITLE
How to open Opencv camera ?

### ISSUE THREAD

**Issue by rawatrob** [Cloudoki/ImageDetectionCordovaPlugin#1]
I'm didn't know the native but working with cordova so how to open the camera by using js/html and how to detect target image/object by js.. ? Please suggested me in cordova

**Comment by a31859** [comment]
Hey @rawatrob, 
the camera opens automatically when you use the plugin on your app. Just add 
```
<preference name="backgroundColor" value="0x00000000" />
```
to your Cordova `config.xml` and on your CSS set the `body` background to transparent.
There's no function to open or to close the camera using JS implemented if that's what you wanted.
To detect a target image you first need to set it using the function `setPatterns` provided by the plugin, then use the `isDetecting` function to know when a image is being detected. Check the [usage example](https://github.com/Cloudoki/ImageDetectionCordovaPlugin#usage-example) to see how this can be done.
