### ISSUE TITLE
Unable to scan more than once

### ISSUE THREAD

**Issue by linuxs** [Cloudoki/ImageDetectionCordovaPlugin#10]
If we scan the same image more than once it says unable to detect image in the console however it is detecting it on the first try. We're unsure if this is a bug within the plugin or a bug within our javascript and we're looking for some pointers.

**Comment by a31859** [comment]
The plugin can detect the same image more then one. After detecting it the first time if the isDetecting error callback is called then if you point it again to the target it should call the isDetecting success callback again.
