### ISSUE TITLE
Error: Invalid Plugin! ../ImageDetectionCordovaPlugin needs a valid package.json

### ISSUE THREAD

**Issue by lebars-r** [Cloudoki/ImageDetectionCordovaPlugin#11]
I followed the instruction wich was 
```
git clone https://github.com/Cloudoki/ImageDetectionCordovaPlugin.git
cd <your-project-root>
cordova plugin add ../ImageDetectionCordovaPlugin
```
But I got the error
```
Error: Invalid Plugin! ../ImageDetectionCordovaPlugin needs a valid package.json
```

my project have been create with the command
```
ionic start myApp tabs
```

What am I doing wrong ? What it's this package.json the error talking about ? what should be inside it ? And in which folder ?

**Comment by a31859** [comment]
Are you using Cordova 7? If you are that might be the issue. The plugin doesn't support Cordova 7 you can try to downgrade to Cordova 6 that should work.

**Comment by lebars-r** [comment]
I use cordova v6.11.0 .
I fixed the issue by creating a package.json with the command
```` plugman createpackagejson . ````
now I am deseperatly try to use it on a ionic 3 context but no luck so far.

**Comment by ltung** [comment]
@lebars-r , Have you had any success in Ionic 3 with the plugin?

**Comment by a31859** [comment]
@lebars-r I haven't tried the plugin with Ionic 3 so I can't be of much help there but the mentioned issue was fixed. Thanks for posting how you fixed it.
