### ISSUE TITLE
Return Matched Rect Info

### ISSUE THREAD

**Issue by wanjungao** [Cloudoki/ImageDetectionCordovaPlugin#14]
It would be cool if the rect info can be returned to the JS.

I tried sample project with Ionic3, seems working. There are one compiling error for IOS ( compare NSNumber with int). 

Adding the plugin into a new Ionic3 project generated error of missing packaging.json.

**Comment by Udanita** [comment]
Right now the plugin is amazing and, yes, it saved my life but, if could be possible to get the position of detected area, will be perfect. Someone has inspected the code and know where to get that data from? Anyways, great job guys!

**Comment by a31859** [comment]
@wanjungao That error was fixed thanks to [Antoine38660](https://github.com/Antoine38660) so it should not show anymore. The plugin was updated and now returns the coordinates of the rect in the `isDetecting` success callback. You'll get something like this:
```json
{
  "message": "pattern detected", 
  "index": 0,
  "coords": {
    "1": { "x": 170.839401, "y": 181.510239 }, 
    "2": { "x": 293.745239, "y": 180.525345 }, 
    "3": { "x": 301.409363, "y": 352.518280 }, 
    "4": { "x": 171.494492, "y": 360.808655 }
  }, 
  "center": {
    "x": 234.956223, "y": 268.231842
  }
}
```
