### ISSUE TITLE
Calling other OpenCV functions?

### ISSUE THREAD

**Issue by tmorone-hookbang** [Cloudoki/ImageDetectionCordovaPlugin#16]
Not a bug, just wondering if you could comment on how easy it would be to extend the plugin to call other OpenCV functions (like canny). Newbie to cordova plugins. Does the included opencv native library include all functions? Thanks.

**Comment by a31859** [comment]
@tmorone-hookbang I think it would be fairly easy to add that functionality but this depends on what you need to do. 
You can look at the `greet` function in this plugin for a simple example (it's similar to the [echo example](https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/) provided by Cordova). 
Regarding the functions yes I think the libraries have the majority of functions if not all.
