### ISSUE TITLE
Manually open and close camera?

### ISSUE THREAD

**Issue by fariskas** [Cloudoki/ImageDetectionCordovaPlugin#17]
Not a bug but just a question.

I tried looking through the instructions and went through the example app but couldnt figure a way to manually open and close the camera.

I was wondering if its possible. And if its not possible out of the box, perhaps point me in the right direction if possible? Pretty new to cordova / app deving. Thanks a bunch!

**Comment by a31859** [comment]
@fariskas I implemented the plugin to start automatically. 
To achieve what you want I think you could use the [`[self camera start];`](https://github.com/Cloudoki/ImageDetectionCordovaPlugin/blob/a1bf91335b84fd279b5bc1cb32f21b1787b96ec3/src/ios/ImageDetectionPlugin.mm#L253) and [`camera.startPreview();`](https://github.com/Cloudoki/ImageDetectionCordovaPlugin/blob/a1bf91335b84fd279b5bc1cb32f21b1787b96ec3/src/android/ImageDetectionPlugin.java#L563) to start the camera in iOS and Android respectivly and use `[self camera stop];` and `camera.stopPreview();` to stop it. That's where I would start from to try to make this functionality.

**Comment by dakados** [comment]
Did you find any solution for this? @fariskas

**Comment by fariskas** [comment]
no i did not unfortunately @dakados
