### ISSUE TITLE
Capture image when detect successfully 

### ISSUE THREAD

**Issue by muhammadsamir11** [Cloudoki/ImageDetectionCordovaPlugin#18]
Hi, I want to get an image when is detecting successfully how can i get base64 image so i can send to server after detect target

**Comment by a31859** [comment]
Hello @muhammadsamir11, when you get the `isDetecting` success callback you get the following data:
```JSON
{
  "message": "pattern detected", 
  "index": 0,
  "coords": {
    "1": { "x": 170.839401, "y": 181.510239 }, 
    "2": { "x": 293.745239, "y": 180.525345 }, 
    "3": { "x": 301.409363, "y": 352.518280 }, 
    "4": { "x": 171.494492, "y": 360.808655 }
  }, 
  "center": {
    "x": 234.956223, "y": 268.231842
  }
}
```
You can use the `index`, since this is the position of the pattern being detected, to get the image.
