### ISSUE TITLE
Can't add plugin to ionic project

### ISSUE THREAD

**Issue by dakados** [Cloudoki/ImageDetectionCordovaPlugin#19]
Hi, I tried adding your plugin in ionic but i keep getting the following error :
Cannot find framework  "/Users/.../plugins/com.cloudoki.imagedetectionplugin/src/ios/opencv2.framework" for plugin com.cloudoki.imagedetectionplugin in iOS platform

I unzipped the opencv2.framework file before, do you have any idea?

**Comment by a31859** [comment]
Hey @dakados, did you extract it before adding the plugin to your project? If so can you check if inside the your project folder in `plugins/com.cloudoki.imagedetectionplugin/src/ios/` to see if the file is there or it's just the zip?

**Comment by dakados** [comment]
Yes I extracted it before.
No the file is not copied into my project folder, just the zip is there after trying to add the plugin.

**Comment by a31859** [comment]
If you add the file to that folder it should work but that's strange if the file was extracted beforehand it should have been copied to the folder.
