### ISSUE TITLE
IOS Webview is not transparent

### ISSUE THREAD

**Issue by hopeter1018** [Cloudoki/ImageDetectionCordovaPlugin#20]
Hello, I am using the ionic 3 and added this plugin. It worked well in android version but I found that the camera is started in IOS but the webview have a black background (I had set almost all html element to background transparent)

**Comment by a31859** [comment]
Hey @hopeter1018, after searching a bit a found [this](https://forum.ionicframework.com/t/transparent-background-for-content-not-working-on-ios/85048/8) could this be the problem you are having?

**Comment by hopeter1018** [comment]
Hello,
Thanks! Let me test it.

* Sorry for my poor english.

**Comment by hopeter1018** [comment]
@a31859 Oh Yes! You are my hero!

**Comment by a31859** [comment]
Glad it solved your problem.
