### ISSUE TITLE
Use plugin in Ionic cordova

### ISSUE THREAD

**Issue by joikolam** [Cloudoki/ImageDetectionCordovaPlugin#21]
Hello i'm new on Ionic, cordova and i would like to know if you have any idea on how to add it and use it on an ionic project. I downloaded the plugin and then added it with the command "cordova plugin add ../ImageDetectionPlugin", it has been added on my project. But it's impossible to use it! So if you have any idea on how i can use it, it would help me a lot! 
Thanks you very much!

**Comment by a31859** [comment]
Hello @joikolam,
You can check the following demo app, it's not up to date and it's for Cordova but I think it can be used has guide to help you on your project. Find it  [here](https://github.com/a31859/ImageDetectionDemoApp)
