### ISSUE TITLE
coords undefined when pattern matched

### ISSUE THREAD

**Issue by aman5537jains** [Cloudoki/ImageDetectionCordovaPlugin#24]
when a pettern match i got coords undefined

**Comment by a31859** [comment]
Hello @aman5537jains, sorry for the late response. 
Is this happening every time it finds a match? 
Was its using Android, iOS, both?!? Which version of Android/iOS? 
Using cordova or ionic?

**Comment by aman5537jains** [comment]
i resolved the issue may be my plugin version is old i checked the git files and my local files some functions are missing in my local java file so i updated that and now its working...

**Comment by a31859** [comment]
Great.
