### ISSUE TITLE
using for OMR(Optical Mark Recognation)

### ISSUE THREAD

**Issue by halilpolathalil** [Cloudoki/ImageDetectionCordovaPlugin#25]
Hi,
Can we use this plugin for OMR(Optical Mark Recognation) of an ionic project? İf it is yes, is there any example for this?

**Comment by a31859** [comment]
Hello @halilpolathalil,

Short answer: no, this plugin only does pattern matching to find if a defined pattern is visible in the camera or not.

Long answer: the plugin uses [OpenCV](https://opencv.org/) to do the pattern matching so if you are familiar with mobile native code and OpenCV then the plugin could be modified to do OMR.

[OMR OpenCV example in python](https://www.pyimagesearch.com/2016/10/03/bubble-sheet-multiple-choice-scanner-and-test-grader-using-omr-python-and-opencv/)

**Comment by halilpolathalil** [comment]
Thank You for your answer.

**Comment by nirandev** [comment]
@halilpolathalil Have you implemented OMR in ionic project? It would be great if you share your experience.
