### ISSUE TITLE
Image subset detection

### ISSUE THREAD

**Issue by parle-g** [Cloudoki/ImageDetectionCordovaPlugin#3]
Hello,
Thanks for developing this.
Before using this plugin, i wanted to know whether this can detect the pattern image which is present inside the camera captured image as subset of the whole captured image. For example a captured image can can have a specific logo along with other image data, which i have to detect. considering my pattern image has only logo.
Will this a valid use case of this plugin.
Appreciate your help.

**Comment by a31859** [comment]
Hey @parle-g, this plugin was made to find/match a pattern in a printed page/image that contained that pattern somewhere on it... So that is a valid use case for it but be aware that depending on the features that the pattern has it may be harder to find the match
