### ISSUE TITLE
Camera opens for less than a second.

### ISSUE THREAD

**Issue by akashs1706** [Cloudoki/ImageDetectionCordovaPlugin#7]
Hello,

I want to  use this plugin in my app. I installed it as per instructions.
I am using your usage example sample, placed it in app.js under  $ionicPlatform.ready(function().

The problem i am facing is when i fresh start the app, the camera opens for less than a second and disappear. how can i increase the timeout limit to detect the images.

**Comment by a31859** [comment]
When the plugin start the camera is usually always open. 
Does the app you are working on have a transparent background? That might be the issue. The camera view is below the webview so if you don't set the background to be transparent then you wont be able to see the camera.

**Comment by akashs1706** [comment]
Thanks. After making it transparent, the camera works fine.
I am wondering if this plugin detects only faces or it can detect any other object other than human faces like any table, chair etc?

**Comment by a31859** [comment]
The plugin was made to find objects using feature matching and homography in a similar way that it's described [here](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.html). So it can detect but the success rate will depend on quality of the features.
