### ISSUE TITLE
Build Failed after a successful installation Intel XDK Android/iOS

### ISSUE THREAD

**Issue by JakKuzie** [Cloudoki/ImageDetectionCordovaPlugin#8]
Hello,
I would like to use this plugin in my Cordova application. I use Intel XDK. Cordova CLI version is 6.2.0. I downloaded and imported plugin (after extracting opencv2.framework from the zip file into the same folder). Adding plugin was successful. After adding plugin I can't build project on Android and iOS.
In android logs I can't see any error. In iOS logs are two errors: 
- .../Plugins/com.cloudoki.imagedetectionplugin/ImageDetectionPlugin/ImageDetectionPlugin.h:2:9: fatal error: 'opencv2/highgui/cap_ios.h' file not found
#import <opencv2/highgui/cap_ios.h>
- .../Plugins/com.cloudoki.imagedetectionplugin/ImageUtils.h:12:10: fatal error: 'opencv2/opencv.hpp' file not found
#include <opencv2/opencv.hpp>

I tried fix it like here: https://stackoverflow.com/questions/12797783/cap-ios-h-is-not-found but it doesn't work. I have installed all Android SDK's and Android SDK  tools. Thank you in advance for your help.

Logs:
[android.logs](https://pastebin.com/JNNxrg7S)
[iOS.logs](https://pastebin.com/aCbGrwrM)

**Comment by a31859** [comment]
Only tested this in Cordova and Ionic but seems to me that the opencv2.framework file was not added to the project. 
Can you check if inside Xcode Frameworks there's the libjpeg.a and opencv2.framework in there? If they are not showing up then that's the problem.
